spring:
  application:
    name: "sistema-escala-paroquia-backend"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgres://localhost/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

